namespace GestorAI.API.DTOs.Fiscal;

public record ConfiguracaoEmpresaResponse(
    Guid Id,
    string? RazaoSocial,
    string? NomeFantasia,
    string? Cnpj,
    string? InscricaoEstadual,
    string? InscricaoMunicipal,
    string? Logradouro,
    string? Numero,
    string? Complemento,
    string? Bairro,
    string? CodigoMunicipio,
    string? Municipio,
    string? Uf,
    string? Cep,
    int? RegimeTributario,
    int? Ambiente,
    int? SerieNfe,
    int? SerieNfce,
    bool TemToken,
    string? Slug,
    string? LogoUrl,
    string? CorPrimaria,
    string? DescricaoPublica);

public record AtualizarConfiguracaoEmpresaRequest(
    string? RazaoSocial,
    string? NomeFantasia,
    string? Cnpj,
    string? InscricaoEstadual,
    string? InscricaoMunicipal,
    string? Logradouro,
    string? Numero,
    string? Complemento,
    string? Bairro,
    string? CodigoMunicipio,
    string? Municipio,
    string? Uf,
    string? Cep,
    int? RegimeTributario,
    string? CscId,
    string? CscToken,
    int? Ambiente,
    int? SerieNfe,
    int? SerieNfce,
    string? FocusNfeToken);
