namespace GestorAI.API.DTOs.Fiscal;

public record ConfiguracaoEmpresaResponse(
    Guid Id,
    string? RazaoSocial,
    string? NomeFantasia,
    string? Cnpj,
    string? InscricaoEstadual,
    string? InscricaoMunicipal,
    string? Phone,
    string? Email,
    string? Logradouro,
    string? Numero,
    string? Complemento,
    string? Bairro,
    string? CodigoMunicipio,
    string? Municipio,
    string? Uf,
    string? Cep,
    int? RegimeTributario,
    int? Ambiente,
    int? SerieNfe,
    int? SerieNfce,
    bool TemToken,
    string? Slug,
    string? LogoUrl,
    string? PrimaryColor,
    string? PublicDescription,
    string? AsaasApiKey,
    bool AsaasSandbox,
    string? ClickSignApiKey,
    bool ClickSignSandbox,
    string? EvolutionApiUrl,
    bool TemEvolutionKey,
    string? EvolutionInstance,
    bool Reminder3DaysBefore,
    bool Reminder1DayBefore,
    bool ReminderOnDueDate,
    bool Reminder1DayAfter,
    bool Reminder3DaysAfter,
    bool Reminder7DaysAfter,
    string? CustomDomain,
    bool AutoApprove,
    decimal? DepositAmount,
    int? CancellationLimitHours,
    string TipoNegocio = "Lojista");

public record SalvarIntegracoesRequest(string? AsaasApiKey, bool AsaasSandbox, string? ClickSignApiKey, bool ClickSignSandbox);

public record SalvarWhiteLabelRequest(
    string? Slug,
    string? LogoUrl,
    string? PrimaryColor,
    string? PublicDescription,
    string? CustomDomain);

public record SalvarAutomacaoConfigRequest(
    string? EvolutionApiUrl,
    string? EvolutionApiKey,
    string? EvolutionInstance,
    bool Reminder3DaysBefore,
    bool Reminder1DayBefore,
    bool ReminderOnDueDate,
    bool Reminder1DayAfter,
    bool Reminder3DaysAfter,
    bool Reminder7DaysAfter);

public record SalvarAgendamentoConfigRequest(
    bool AutoApprove,
    decimal? DepositAmount,
    int? CancellationLimitHours);

public record AtualizarConfiguracaoEmpresaRequest(
    string? RazaoSocial,
    string? NomeFantasia,
    string? Cnpj,
    string? InscricaoEstadual,
    string? InscricaoMunicipal,
    string? Logradouro,
    string? Numero,
    string? Complemento,
    string? Bairro,
    string? CodigoMunicipio,
    string? Municipio,
    string? Uf,
    string? Cep,
    int? RegimeTributario,
    string? CscId,
    string? CscToken,
    int? Ambiente,
    int? SerieNfe,
    int? SerieNfce,
    string? FocusNfeToken,
    string? Phone = null,
    string? Email = null,
    string? TipoNegocio = null);
