// <auto-generated />
using System;
using GestorAI.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestorAI.API.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gestor")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_phone");

                    b.Property<string>("DepositAsaasId")
                        .HasColumnType("text")
                        .HasColumnName("deposit_asaas_id");

                    b.Property<bool>("DepositPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("deposit_paid");

                    b.Property<string>("DepositPixQrCode")
                        .HasColumnType("text")
                        .HasColumnName("deposit_pix_qr_code");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<Guid?>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_appointments");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_appointments_customer_id");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("ix_appointments_professional_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_appointments_service_id");

                    b.ToTable("appointments", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.AutomationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("charge_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.HasKey("Id")
                        .HasName("pk_automation_logs");

                    b.HasIndex("ChargeId", "EventType")
                        .HasDatabaseName("ix_automation_logs_charge_id_event_type");

                    b.ToTable("automation_logs", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Charge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("AsaasBoletoUrl")
                        .HasColumnType("text")
                        .HasColumnName("asaas_boleto_url");

                    b.Property<string>("AsaasId")
                        .HasColumnType("text")
                        .HasColumnName("asaas_id");

                    b.Property<string>("AsaasPaymentLink")
                        .HasColumnType("text")
                        .HasColumnName("asaas_payment_link");

                    b.Property<string>("AsaasPixQrCode")
                        .HasColumnType("text")
                        .HasColumnName("asaas_pix_qr_code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("payment_date");

                    b.Property<int?>("PaymentMethod")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_charges");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_charges_contract_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_charges_customer_id");

                    b.ToTable("charges", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.CompanySettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Ambiente")
                        .HasColumnType("integer")
                        .HasColumnName("ambiente");

                    b.Property<string>("AsaasApiKey")
                        .HasColumnType("text")
                        .HasColumnName("asaas_api_key");

                    b.Property<bool>("AsaasSandbox")
                        .HasColumnType("boolean")
                        .HasColumnName("asaas_sandbox");

                    b.Property<bool>("AutoApprove")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_approve");

                    b.Property<string>("Bairro")
                        .HasColumnType("text")
                        .HasColumnName("bairro");

                    b.Property<int?>("CancellationLimitHours")
                        .HasColumnType("integer")
                        .HasColumnName("cancellation_limit_hours");

                    b.Property<string>("Cep")
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<string>("ClickSignApiKey")
                        .HasColumnType("text")
                        .HasColumnName("click_sign_api_key");

                    b.Property<bool>("ClickSignSandbox")
                        .HasColumnType("boolean")
                        .HasColumnName("click_sign_sandbox");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text")
                        .HasColumnName("cnpj");

                    b.Property<string>("CodigoMunicipio")
                        .HasColumnType("text")
                        .HasColumnName("codigo_municipio");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Complemento")
                        .HasColumnType("text")
                        .HasColumnName("complemento");

                    b.Property<string>("CscId")
                        .HasColumnType("text")
                        .HasColumnName("csc_id");

                    b.Property<string>("CscToken")
                        .HasColumnType("text")
                        .HasColumnName("csc_token");

                    b.Property<string>("CustomDomain")
                        .HasColumnType("text")
                        .HasColumnName("custom_domain");

                    b.Property<decimal?>("DepositAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("deposit_amount");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EvolutionApiKey")
                        .HasColumnType("text")
                        .HasColumnName("evolution_api_key");

                    b.Property<string>("EvolutionApiUrl")
                        .HasColumnType("text")
                        .HasColumnName("evolution_api_url");

                    b.Property<string>("EvolutionInstance")
                        .HasColumnType("text")
                        .HasColumnName("evolution_instance");

                    b.Property<string>("FocusNfeToken")
                        .HasColumnType("text")
                        .HasColumnName("focus_nfe_token");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("text")
                        .HasColumnName("inscricao_estadual");

                    b.Property<string>("InscricaoMunicipal")
                        .HasColumnType("text")
                        .HasColumnName("inscricao_municipal");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Logradouro")
                        .HasColumnType("text")
                        .HasColumnName("logradouro");

                    b.Property<string>("Municipio")
                        .HasColumnType("text")
                        .HasColumnName("municipio");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("text")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("Numero")
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PrimaryColor")
                        .HasColumnType("text")
                        .HasColumnName("primary_color");

                    b.Property<string>("PublicDescription")
                        .HasColumnType("text")
                        .HasColumnName("public_description");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("text")
                        .HasColumnName("razao_social");

                    b.Property<int?>("RegimeTributario")
                        .HasColumnType("integer")
                        .HasColumnName("regime_tributario");

                    b.Property<bool>("Reminder1DayAfter")
                        .HasColumnType("boolean")
                        .HasColumnName("reminder1day_after");

                    b.Property<bool>("Reminder1DayBefore")
                        .HasColumnType("boolean")
                        .HasColumnName("reminder1day_before");

                    b.Property<bool>("Reminder3DaysAfter")
                        .HasColumnType("boolean")
                        .HasColumnName("reminder3days_after");

                    b.Property<bool>("Reminder3DaysBefore")
                        .HasColumnType("boolean")
                        .HasColumnName("reminder3days_before");

                    b.Property<bool>("Reminder7DaysAfter")
                        .HasColumnType("boolean")
                        .HasColumnName("reminder7days_after");

                    b.Property<bool>("ReminderOnDueDate")
                        .HasColumnType("boolean")
                        .HasColumnName("reminder_on_due_date");

                    b.Property<int?>("SerieNfce")
                        .HasColumnType("integer")
                        .HasColumnName("serie_nfce");

                    b.Property<int?>("SerieNfe")
                        .HasColumnType("integer")
                        .HasColumnName("serie_nfe");

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("TipoNegocio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_negocio");

                    b.Property<string>("Uf")
                        .HasColumnType("text")
                        .HasColumnName("uf");

                    b.HasKey("Id")
                        .HasName("pk_company_settings");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_company_settings_slug")
                        .HasFilter("\"Slug\" IS NOT NULL");

                    b.ToTable("company_settings", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int>("ChargeType")
                        .HasColumnType("integer")
                        .HasColumnName("charge_type");

                    b.Property<string>("ClickSignDocKey")
                        .HasColumnType("text")
                        .HasColumnName("click_sign_doc_key");

                    b.Property<string>("ClickSignStatus")
                        .HasColumnType("text")
                        .HasColumnName("click_sign_status");

                    b.Property<string>("ClickSignViewerUrl")
                        .HasColumnType("text")
                        .HasColumnName("click_sign_viewer_url");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid?>("CustomerSubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_subscription_id");

                    b.Property<int>("DueDay")
                        .HasColumnType("integer")
                        .HasColumnName("due_day");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_contracts_customer_id");

                    b.ToTable("contracts", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.ContractItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_contract_item");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_contract_item_contract_id");

                    b.ToTable("contract_item", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.ContractTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChargeType")
                        .HasColumnType("integer")
                        .HasColumnName("charge_type");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DefaultAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("default_amount");

                    b.Property<int>("DueDay")
                        .HasColumnType("integer")
                        .HasColumnName("due_day");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_contract_templates");

                    b.ToTable("contract_templates", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.ContractTemplateItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_template_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_contract_template_items");

                    b.HasIndex("ContractTemplateId")
                        .HasDatabaseName("ix_contract_template_items_contract_template_id");

                    b.ToTable("contract_template_items", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("whats_app");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("CompanyId", "WhatsApp")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_company_id_whats_app");

                    b.ToTable("customers", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.CustomerSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentCycle")
                        .HasColumnType("integer")
                        .HasColumnName("current_cycle");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("RenewalDate")
                        .HasColumnType("date")
                        .HasColumnName("renewal_date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_plan_id");

                    b.HasKey("Id")
                        .HasName("pk_customer_subscriptions");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_customer_subscriptions_contract_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_subscriptions_customer_id");

                    b.HasIndex("SubscriptionPlanId")
                        .HasDatabaseName("ix_customer_subscriptions_subscription_plan_id");

                    b.ToTable("customer_subscriptions", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.DashboardLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WidgetsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("widgets_json");

                    b.HasKey("Id")
                        .HasName("pk_dashboard_layouts");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasDatabaseName("ix_dashboard_layouts_company_id");

                    b.ToTable("dashboard_layouts", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.InstallmentPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("InstallmentCount")
                        .HasColumnType("integer")
                        .HasColumnName("installment_count");

                    b.Property<Guid?>("PurchaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_installment_plans");

                    b.HasIndex("PurchaseId")
                        .IsUnique()
                        .HasDatabaseName("ix_installment_plans_purchase_id");

                    b.ToTable("installment_plans", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessKey")
                        .HasColumnType("text")
                        .HasColumnName("access_key");

                    b.Property<DateTime?>("AuthorizedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("authorized_at");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("canceled_at");

                    b.Property<string>("CancellationProtocol")
                        .HasColumnType("text")
                        .HasColumnName("cancellation_protocol");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("FocusNfeId")
                        .HasColumnType("text")
                        .HasColumnName("focus_nfe_id");

                    b.Property<string>("FocusNfeRef")
                        .HasColumnType("text")
                        .HasColumnName("focus_nfe_ref");

                    b.Property<int>("Model")
                        .HasColumnType("integer")
                        .HasColumnName("model");

                    b.Property<int?>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("text")
                        .HasColumnName("pdf_url");

                    b.Property<string>("Protocol")
                        .HasColumnType("text")
                        .HasColumnName("protocol");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.Property<int?>("Series")
                        .HasColumnType("integer")
                        .HasColumnName("series");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("XmlUrl")
                        .HasColumnType("text")
                        .HasColumnName("xml_url");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_invoices_sale_id");

                    b.ToTable("invoices", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.InvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cfop")
                        .HasColumnType("text")
                        .HasColumnName("cfop");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Ncm")
                        .HasColumnType("text")
                        .HasColumnName("ncm");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_invoice_items");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_invoice_items_invoice_id");

                    b.ToTable("invoice_items", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.NicheTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("BestSeller")
                        .HasColumnType("boolean")
                        .HasColumnName("best_seller");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<string>("Niche")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("niche");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan_name");

                    b.Property<decimal>("SuggestedPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("suggested_price");

                    b.HasKey("Id")
                        .HasName("pk_niche_templates");

                    b.ToTable("niche_templates", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.NicheTemplateItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_percentage");

                    b.Property<Guid>("NicheTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("niche_template_id");

                    b.Property<int>("QuantityPerCycle")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_per_cycle");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_niche_template_items");

                    b.HasIndex("NicheTemplateId")
                        .HasDatabaseName("ix_niche_template_items_niche_template_id");

                    b.ToTable("niche_template_items", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AverageCost")
                        .HasColumnType("numeric")
                        .HasColumnName("average_cost");

                    b.Property<string>("Barcode")
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentStock")
                        .HasColumnType("numeric")
                        .HasColumnName("current_stock");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("MinimumStock")
                        .HasColumnType("numeric")
                        .HasColumnName("minimum_stock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("sale_price");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.ToTable("products", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Professional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_professionals");

                    b.ToTable("professionals", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<string>("NoteNumber")
                        .HasColumnType("text")
                        .HasColumnName("note_number");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_terms");

                    b.Property<Guid?>("PurchaseOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_id");

                    b.Property<string>("PurchaseType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purchase_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_purchases");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("ix_purchases_purchase_order_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_purchases_supplier_id");

                    b.ToTable("purchases", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.PurchaseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AllocatedFreight")
                        .HasColumnType("numeric")
                        .HasColumnName("allocated_freight");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CostCenter")
                        .HasColumnType("text")
                        .HasColumnName("cost_center");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Destination")
                        .HasColumnType("integer")
                        .HasColumnName("destination");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount");

                    b.Property<string>("FinancialCategory")
                        .HasColumnType("text")
                        .HasColumnName("financial_category");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("numeric")
                        .HasColumnName("taxes");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_purchase_items");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_purchase_items_product_id");

                    b.HasIndex("PurchaseId")
                        .HasDatabaseName("ix_purchase_items_purchase_id");

                    b.ToTable("purchase_items", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<decimal>("EstimatedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_amount");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("pk_purchase_orders");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_purchase_orders_supplier_id");

                    b.ToTable("purchase_orders", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.PurchaseOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("EstimatedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_amount");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_purchase_order_items");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_purchase_order_items_product_id");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("ix_purchase_order_items_purchase_order_id");

                    b.ToTable("purchase_order_items", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expiration_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<Guid?>("PublicToken")
                        .HasColumnType("uuid")
                        .HasColumnName("public_token");

                    b.Property<Guid?>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_quotes");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_quotes_customer_id");

                    b.ToTable("quotes", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.QuoteItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_quote_items");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_quote_items_product_id");

                    b.HasIndex("QuoteId")
                        .HasDatabaseName("ix_quote_items_quote_id");

                    b.ToTable("quote_items", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.ReportLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("TabsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tabs_json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_report_layouts");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasDatabaseName("ix_report_layouts_company_id");

                    b.ToTable("report_layouts", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount");

                    b.Property<int?>("Installments")
                        .HasColumnType("integer")
                        .HasColumnName("installments");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method");

                    b.Property<Guid?>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<string>("ProfessionalName")
                        .HasColumnType("text")
                        .HasColumnName("professional_name");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sale_date");

                    b.Property<string>("ServiceOrderNotes")
                        .HasColumnType("text")
                        .HasColumnName("observacao_os");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_sales");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_sales_customer_id");

                    b.ToTable("sales", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.SaleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_sale_items");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_sale_items_product_id");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_sale_items_sale_id");

                    b.ToTable("sale_items", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.ScheduleBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid?>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_schedule_blocks");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("ix_schedule_blocks_professional_id");

                    b.ToTable("schedule_blocks", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("movement_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_stock_movements");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_stock_movements_product_id");

                    b.ToTable("stock_movements", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("BestSeller")
                        .HasColumnType("boolean")
                        .HasColumnName("best_seller");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Niche")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("niche");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("pk_subscription_plans");

                    b.ToTable("subscription_plans", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.SubscriptionPlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_percentage");

                    b.Property<int>("QuantityPerCycle")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_per_cycle");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_plan_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_subscription_plan_items");

                    b.HasIndex("SubscriptionPlanId")
                        .HasDatabaseName("ix_subscription_plan_items_subscription_plan_id");

                    b.ToTable("subscription_plan_items", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cep")
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("CnpjCpf")
                        .HasColumnType("text")
                        .HasColumnName("cnpj_cpf");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text")
                        .HasColumnName("contact_person");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("text")
                        .HasColumnName("inscricao_estadual");

                    b.Property<string>("Logradouro")
                        .HasColumnType("text")
                        .HasColumnName("logradouro");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("text")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("text")
                        .HasColumnName("razao_social");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Uf")
                        .HasColumnType("text")
                        .HasColumnName("uf");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("text")
                        .HasColumnName("whats_app");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.HasIndex("CompanyId", "CnpjCpf")
                        .IsUnique()
                        .HasDatabaseName("ix_suppliers_company_id_cnpj_cpf")
                        .HasFilter("\"CnpjCpf\" IS NOT NULL");

                    b.ToTable("suppliers", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("due_date");

                    b.Property<int?>("InstallmentNumber")
                        .HasColumnType("integer")
                        .HasColumnName("installment_number");

                    b.Property<Guid?>("InstallmentPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("installment_plan_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("payment_date");

                    b.Property<Guid?>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("InstallmentPlanId")
                        .HasDatabaseName("ix_transactions_installment_plan_id");

                    b.HasIndex("SaleId")
                        .IsUnique()
                        .HasDatabaseName("ix_transactions_sale_id");

                    b.ToTable("transactions", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.TransactionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_transaction_categories");

                    b.HasIndex("CompanyId", "Type", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_transaction_categories_company_id_type_name");

                    b.ToTable("transaction_categories", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.WeeklyAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.Property<int>("WeekDay")
                        .HasColumnType("integer")
                        .HasColumnName("week_day");

                    b.HasKey("Id")
                        .HasName("pk_weekly_availabilities");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("ix_weekly_availabilities_professional_id");

                    b.ToTable("weekly_availabilities", "gestor");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("fk_appointments_customers_customer_id");

                    b.HasOne("GestorAI.API.Domain.Entities.Professional", "Professional")
                        .WithMany("Appointments")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_professionals_professional_id");

                    b.HasOne("GestorAI.API.Domain.Entities.Product", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_products_service_id");

                    b.Navigation("Customer");

                    b.Navigation("Professional");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Charge", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Contract", "Contract")
                        .WithMany("Charges")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("fk_charges_contracts_contract_id");

                    b.HasOne("GestorAI.API.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_charges_customers_customer_id");

                    b.Navigation("Contract");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Contract", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.ContractItem", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Contract", null)
                        .WithMany("Items")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_item_contracts_contract_id");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.ContractTemplateItem", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.ContractTemplate", null)
                        .WithMany("Items")
                        .HasForeignKey("ContractTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_template_items_contract_templates_contract_templat");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.CustomerSubscription", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_subscriptions_contracts_contract_id");

                    b.HasOne("GestorAI.API.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_subscriptions_customers_customer_id");

                    b.HasOne("GestorAI.API.Domain.Entities.SubscriptionPlan", "Plan")
                        .WithMany("Subscribers")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_subscriptions_subscription_plans_subscription_plan");

                    b.Navigation("Contract");

                    b.Navigation("Customer");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.InstallmentPlan", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Purchase", "Purchase")
                        .WithOne("InstallmentPlan")
                        .HasForeignKey("GestorAI.API.Domain.Entities.InstallmentPlan", "PurchaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_installment_plans_purchases_purchase_id");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Sale", "Sale")
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_sales_sale_id");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.InvoiceItem", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_items_invoices_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.NicheTemplateItem", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.NicheTemplate", "Template")
                        .WithMany("Items")
                        .HasForeignKey("NicheTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_niche_template_items_niche_templates_niche_template_id");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Product", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Purchase", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_purchases_purchase_orders_purchase_order_id");

                    b.HasOne("GestorAI.API.Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchases_suppliers_supplier_id");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.PurchaseItem", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_purchase_items_products_product_id");

                    b.HasOne("GestorAI.API.Domain.Entities.Purchase", "Purchase")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_items_purchases_purchase_id");

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_orders_suppliers_supplier_id");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.PurchaseOrderItem", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_purchase_order_items_products_product_id");

                    b.HasOne("GestorAI.API.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_items_purchase_orders_purchase_order_id");

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Quote", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("fk_quotes_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.QuoteItem", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_quote_items_products_product_id");

                    b.HasOne("GestorAI.API.Domain.Entities.Quote", "Quote")
                        .WithMany("Items")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quote_items_quotes_quote_id");

                    b.Navigation("Product");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Sale", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("fk_sales_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.SaleItem", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Product", "Product")
                        .WithMany("SaleItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_items_products_product_id");

                    b.HasOne("GestorAI.API.Domain.Entities.Sale", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_items_sales_sale_id");

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.ScheduleBlock", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Professional", "Professional")
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .HasConstraintName("fk_schedule_blocks_professionals_professional_id");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Product", "Product")
                        .WithMany("StockMovements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movements_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.SubscriptionPlanItem", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.SubscriptionPlan", "Plan")
                        .WithMany("Items")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_plan_items_subscription_plans_subscription_pla");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.InstallmentPlan", "InstallmentPlan")
                        .WithMany("Installments")
                        .HasForeignKey("InstallmentPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_installment_plans_installment_plan_id");

                    b.HasOne("GestorAI.API.Domain.Entities.Sale", "Sale")
                        .WithOne("Transaction")
                        .HasForeignKey("GestorAI.API.Domain.Entities.Transaction", "SaleId")
                        .HasConstraintName("fk_transactions_sales_sale_id");

                    b.Navigation("InstallmentPlan");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.WeeklyAvailability", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Professional", "Professional")
                        .WithMany("Availabilities")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weekly_availabilities_professionals_professional_id");

                    b.Navigation("Professional");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Contract", b =>
                {
                    b.Navigation("Charges");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.ContractTemplate", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.InstallmentPlan", b =>
                {
                    b.Navigation("Installments");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.NicheTemplate", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Product", b =>
                {
                    b.Navigation("SaleItems");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Professional", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Availabilities");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Purchase", b =>
                {
                    b.Navigation("InstallmentPlan");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Quote", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Sale", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Subscribers");
                });
#pragma warning restore 612, 618
        }
    }
}
