// <auto-generated />
using System;
using GestorAI.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestorAI.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610011437_AddCategoriaLancamento")]
    partial class AddCategoriaLancamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cliente_nome");

                    b.Property<string>("ClienteTelefone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cliente_telefone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_hora_fim");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_hora_inicio");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("profissional_id");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("servico_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("VendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venda_id");

                    b.HasKey("Id")
                        .HasName("pk_agendamentos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_agendamentos_cliente_id");

                    b.HasIndex("ProfissionalId")
                        .HasDatabaseName("ix_agendamentos_profissional_id");

                    b.HasIndex("ServicoId")
                        .HasDatabaseName("ix_agendamentos_servico_id");

                    b.ToTable("agendamentos", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.AutomacaoLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CobrancaId")
                        .HasColumnType("uuid")
                        .HasColumnName("cobranca_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("ErroMsg")
                        .HasColumnType("text")
                        .HasColumnName("erro_msg");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("boolean")
                        .HasColumnName("sucesso");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_evento");

                    b.HasKey("Id")
                        .HasName("pk_automacao_logs");

                    b.HasIndex("CobrancaId", "TipoEvento")
                        .HasDatabaseName("ix_automacao_logs_cobranca_id_tipo_evento");

                    b.ToTable("automacao_logs", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.BloqueioAgenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_inicio");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<Guid?>("ProfissionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("profissional_id");

                    b.HasKey("Id")
                        .HasName("pk_bloqueios_agenda");

                    b.HasIndex("ProfissionalId")
                        .HasDatabaseName("ix_bloqueios_agenda_profissional_id");

                    b.ToTable("bloqueios_agenda", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.CategoriaLancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_categorias_lancamento");

                    b.HasIndex("EmpresaId", "Tipo", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_lancamento_empresa_id_tipo_nome");

                    b.ToTable("categorias_lancamento", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Whatsapp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("EmpresaId", "Whatsapp")
                        .IsUnique()
                        .HasDatabaseName("ix_clientes_empresa_id_whatsapp");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Cobranca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AsaasBoletoUrl")
                        .HasColumnType("text")
                        .HasColumnName("asaas_boleto_url");

                    b.Property<string>("AsaasId")
                        .HasColumnType("text")
                        .HasColumnName("asaas_id");

                    b.Property<string>("AsaasPaymentLink")
                        .HasColumnType("text")
                        .HasColumnName("asaas_payment_link");

                    b.Property<string>("AsaasPixQrCode")
                        .HasColumnType("text")
                        .HasColumnName("asaas_pix_qr_code");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<Guid?>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_pagamento");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<int?>("FormaPagamento")
                        .HasColumnType("integer")
                        .HasColumnName("forma_pagamento");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("referencia");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_cobrancas");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_cobrancas_cliente_id");

                    b.HasIndex("ContratoId")
                        .HasDatabaseName("ix_cobrancas_contrato_id");

                    b.ToTable("cobrancas", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.ConfiguracaoEmpresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Ambiente")
                        .HasColumnType("integer")
                        .HasColumnName("ambiente");

                    b.Property<string>("AsaasApiKey")
                        .HasColumnType("text")
                        .HasColumnName("asaas_api_key");

                    b.Property<bool>("AsaasSandbox")
                        .HasColumnType("boolean")
                        .HasColumnName("asaas_sandbox");

                    b.Property<string>("Bairro")
                        .HasColumnType("text")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text")
                        .HasColumnName("cnpj");

                    b.Property<string>("CodigoMunicipio")
                        .HasColumnType("text")
                        .HasColumnName("codigo_municipio");

                    b.Property<string>("Complemento")
                        .HasColumnType("text")
                        .HasColumnName("complemento");

                    b.Property<string>("CorPrimaria")
                        .HasColumnType("text")
                        .HasColumnName("cor_primaria");

                    b.Property<string>("CscId")
                        .HasColumnType("text")
                        .HasColumnName("csc_id");

                    b.Property<string>("CscToken")
                        .HasColumnType("text")
                        .HasColumnName("csc_token");

                    b.Property<string>("DescricaoPublica")
                        .HasColumnType("text")
                        .HasColumnName("descricao_publica");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("EvolutionApiKey")
                        .HasColumnType("text")
                        .HasColumnName("evolution_api_key");

                    b.Property<string>("EvolutionApiUrl")
                        .HasColumnType("text")
                        .HasColumnName("evolution_api_url");

                    b.Property<string>("EvolutionInstance")
                        .HasColumnType("text")
                        .HasColumnName("evolution_instance");

                    b.Property<string>("FocusNfeToken")
                        .HasColumnType("text")
                        .HasColumnName("focus_nfe_token");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("text")
                        .HasColumnName("inscricao_estadual");

                    b.Property<string>("InscricaoMunicipal")
                        .HasColumnType("text")
                        .HasColumnName("inscricao_municipal");

                    b.Property<bool>("Lembrete1dAntes")
                        .HasColumnType("boolean")
                        .HasColumnName("lembrete1d_antes");

                    b.Property<bool>("Lembrete1dDepois")
                        .HasColumnType("boolean")
                        .HasColumnName("lembrete1d_depois");

                    b.Property<bool>("Lembrete3dAntes")
                        .HasColumnType("boolean")
                        .HasColumnName("lembrete3d_antes");

                    b.Property<bool>("Lembrete3dDepois")
                        .HasColumnType("boolean")
                        .HasColumnName("lembrete3d_depois");

                    b.Property<bool>("Lembrete7dDepois")
                        .HasColumnType("boolean")
                        .HasColumnName("lembrete7d_depois");

                    b.Property<bool>("LembreteNoDia")
                        .HasColumnType("boolean")
                        .HasColumnName("lembrete_no_dia");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Logradouro")
                        .HasColumnType("text")
                        .HasColumnName("logradouro");

                    b.Property<string>("Municipio")
                        .HasColumnType("text")
                        .HasColumnName("municipio");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("text")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("Numero")
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("text")
                        .HasColumnName("razao_social");

                    b.Property<int?>("RegimeTributario")
                        .HasColumnType("integer")
                        .HasColumnName("regime_tributario");

                    b.Property<int?>("SerieNfce")
                        .HasColumnType("integer")
                        .HasColumnName("serie_nfce");

                    b.Property<int?>("SerieNfe")
                        .HasColumnType("integer")
                        .HasColumnName("serie_nfe");

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Uf")
                        .HasColumnType("text")
                        .HasColumnName("uf");

                    b.HasKey("Id")
                        .HasName("pk_configuracoes_empresa");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_configuracoes_empresa_slug")
                        .HasFilter("\"Slug\" IS NOT NULL");

                    b.ToTable("configuracoes_empresa", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_vencimento");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Objeto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("objeto");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<int>("Periodicidade")
                        .HasColumnType("integer")
                        .HasColumnName("periodicidade");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TipoCobranca")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_cobranca");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_contratos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_contratos_cliente_id");

                    b.ToTable("contratos", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.ContratoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id")
                        .HasName("pk_contrato_itens");

                    b.HasIndex("ContratoId")
                        .HasDatabaseName("ix_contrato_itens_contrato_id");

                    b.ToTable("ContratoItens", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.ContratoTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_vencimento");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Objeto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("objeto");

                    b.Property<int>("Periodicidade")
                        .HasColumnType("integer")
                        .HasColumnName("periodicidade");

                    b.Property<int>("TipoCobranca")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_cobranca");

                    b.Property<decimal?>("ValorPadrao")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_padrao");

                    b.HasKey("Id")
                        .HasName("pk_contrato_templates");

                    b.ToTable("contrato_templates", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.ContratoTemplateItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContratoTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_template_id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id")
                        .HasName("pk_contrato_template_itens");

                    b.HasIndex("ContratoTemplateId")
                        .HasDatabaseName("ix_contrato_template_itens_contrato_template_id");

                    b.ToTable("ContratoTemplateItens", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.DisponibilidadeSemanal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer")
                        .HasColumnName("dia_semana");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("interval")
                        .HasColumnName("hora_fim");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval")
                        .HasColumnName("hora_inicio");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("profissional_id");

                    b.HasKey("Id")
                        .HasName("pk_disponibilidade_semanais");

                    b.HasIndex("ProfissionalId")
                        .HasDatabaseName("ix_disponibilidade_semanais_profissional_id");

                    b.ToTable("disponibilidade_semanais", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cep")
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasColumnType("text")
                        .HasColumnName("cidade");

                    b.Property<string>("CnpjCpf")
                        .HasColumnType("text")
                        .HasColumnName("cnpj_cpf");

                    b.Property<string>("Contato")
                        .HasColumnType("text")
                        .HasColumnName("contato");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Logradouro")
                        .HasColumnType("text")
                        .HasColumnName("logradouro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<string>("Uf")
                        .HasColumnType("text")
                        .HasColumnName("uf");

                    b.HasKey("Id")
                        .HasName("pk_fornecedores");

                    b.HasIndex("EmpresaId", "CnpjCpf")
                        .IsUnique()
                        .HasDatabaseName("ix_fornecedores_empresa_id_cnpj_cpf")
                        .HasFilter("\"CnpjCpf\" IS NOT NULL");

                    b.ToTable("fornecedores", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.ItemVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("numeric")
                        .HasColumnName("desconto");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_unitario");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venda_id");

                    b.HasKey("Id")
                        .HasName("pk_itens_venda");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_itens_venda_produto_id");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("ix_itens_venda_venda_id");

                    b.ToTable("itens_venda", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_pagamento");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.Property<Guid?>("VendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venda_id");

                    b.HasKey("Id")
                        .HasName("pk_lancamentos");

                    b.HasIndex("VendaId")
                        .IsUnique()
                        .HasDatabaseName("ix_lancamentos_venda_id");

                    b.ToTable("lancamentos", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.MovimentacaoEstoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_hora");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<int>("Origem")
                        .HasColumnType("integer")
                        .HasColumnName("origem");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidade");

                    b.Property<Guid?>("ReferenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("referencia_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_movimentacoes_estoque");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_movimentacoes_estoque_produto_id");

                    b.ToTable("movimentacoes_estoque", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.NotaFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AutorizadaEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("autorizada_em");

                    b.Property<DateTime?>("CanceladaEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("cancelada_em");

                    b.Property<string>("ChaveAcesso")
                        .HasColumnType("text")
                        .HasColumnName("chave_acesso");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criada_em");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("FocusNfeId")
                        .HasColumnType("text")
                        .HasColumnName("focus_nfe_id");

                    b.Property<string>("FocusNfeRef")
                        .HasColumnType("text")
                        .HasColumnName("focus_nfe_ref");

                    b.Property<string>("MensagemErro")
                        .HasColumnType("text")
                        .HasColumnName("mensagem_erro");

                    b.Property<int>("Modelo")
                        .HasColumnType("integer")
                        .HasColumnName("modelo");

                    b.Property<int?>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("text")
                        .HasColumnName("pdf_url");

                    b.Property<string>("Protocolo")
                        .HasColumnType("text")
                        .HasColumnName("protocolo");

                    b.Property<string>("ProtocoloCancelamento")
                        .HasColumnType("text")
                        .HasColumnName("protocolo_cancelamento");

                    b.Property<int?>("Serie")
                        .HasColumnType("integer")
                        .HasColumnName("serie");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venda_id");

                    b.Property<string>("XmlUrl")
                        .HasColumnType("text")
                        .HasColumnName("xml_url");

                    b.HasKey("Id")
                        .HasName("pk_notas_fiscais");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("ix_notas_fiscais_venda_id");

                    b.ToTable("notas_fiscais", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.NotaFiscalItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cfop")
                        .HasColumnType("text")
                        .HasColumnName("cfop");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Ncm")
                        .HasColumnType("text")
                        .HasColumnName("ncm");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_produto");

                    b.Property<Guid>("NotaFiscalId")
                        .HasColumnType("uuid")
                        .HasColumnName("nota_fiscal_id");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_unitario");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_nota_fiscal_itens");

                    b.HasIndex("NotaFiscalId")
                        .HasDatabaseName("ix_nota_fiscal_itens_nota_fiscal_id");

                    b.ToTable("nota_fiscal_itens", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Orcamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_validade");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.Property<Guid?>("TokenPublico")
                        .HasColumnType("uuid")
                        .HasColumnName("token_publico");

                    b.Property<Guid?>("VendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venda_id");

                    b.HasKey("Id")
                        .HasName("pk_orcamentos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_orcamentos_cliente_id");

                    b.ToTable("orcamentos", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.OrcamentoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<Guid>("OrcamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("orcamento_id");

                    b.Property<Guid?>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidade");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id")
                        .HasName("pk_orcamento_itens");

                    b.HasIndex("OrcamentoId")
                        .HasDatabaseName("ix_orcamento_itens_orcamento_id");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_orcamento_itens_produto_id");

                    b.ToTable("orcamento_itens", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<string>("CodigoBarras")
                        .HasColumnType("text")
                        .HasColumnName("codigo_barras");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<decimal>("CustoMedio")
                        .HasColumnType("numeric")
                        .HasColumnName("custo_medio");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int?>("DuracaoMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_minutos");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<decimal>("EstoqueAtual")
                        .HasColumnType("numeric")
                        .HasColumnName("estoque_atual");

                    b.Property<decimal>("EstoqueMinimo")
                        .HasColumnType("numeric")
                        .HasColumnName("estoque_minimo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_venda");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_produtos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_produtos_categoria_id");

                    b.ToTable("produtos", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Profissional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_profissionais");

                    b.ToTable("profissionais", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_hora");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("numeric")
                        .HasColumnName("desconto");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<int>("FormaPagamento")
                        .HasColumnType("integer")
                        .HasColumnName("forma_pagamento");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<int?>("Parcelas")
                        .HasColumnType("integer")
                        .HasColumnName("parcelas");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_vendas");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_vendas_cliente_id");

                    b.ToTable("vendas", (string)null);
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Agendamento", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .HasConstraintName("fk_agendamentos_clientes_cliente_id");

                    b.HasOne("GestorAI.API.Domain.Entities.Profissional", "Profissional")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agendamentos_profissionais_profissional_id");

                    b.HasOne("GestorAI.API.Domain.Entities.Produto", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agendamentos_produtos_servico_id");

                    b.Navigation("Cliente");

                    b.Navigation("Profissional");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.BloqueioAgenda", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Profissional", "Profissional")
                        .WithMany()
                        .HasForeignKey("ProfissionalId")
                        .HasConstraintName("fk_bloqueios_agenda_profissionais_profissional_id");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Cobranca", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cobrancas_clientes_cliente_id");

                    b.HasOne("GestorAI.API.Domain.Entities.Contrato", "Contrato")
                        .WithMany("Cobrancas")
                        .HasForeignKey("ContratoId")
                        .HasConstraintName("fk_cobrancas_contratos_contrato_id");

                    b.Navigation("Cliente");

                    b.Navigation("Contrato");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Contrato", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contratos_clientes_cliente_id");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.ContratoItem", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Contrato", null)
                        .WithMany("Itens")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contrato_itens_contratos_contrato_id");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.ContratoTemplateItem", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.ContratoTemplate", null)
                        .WithMany("Itens")
                        .HasForeignKey("ContratoTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contrato_template_itens_contrato_templates_contrato_template_");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.DisponibilidadeSemanal", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Profissional", "Profissional")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_disponibilidade_semanais_profissionais_profissional_id");

                    b.Navigation("Profissional");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.ItemVenda", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Produto", "Produto")
                        .WithMany("ItensVenda")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itens_venda_produtos_produto_id");

                    b.HasOne("GestorAI.API.Domain.Entities.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itens_venda_vendas_venda_id");

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Lancamento", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Venda", "Venda")
                        .WithOne("Lancamento")
                        .HasForeignKey("GestorAI.API.Domain.Entities.Lancamento", "VendaId")
                        .HasConstraintName("fk_lancamentos_vendas_venda_id");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.MovimentacaoEstoque", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Produto", "Produto")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacoes_estoque_produtos_produto_id");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.NotaFiscal", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notas_fiscais_vendas_venda_id");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.NotaFiscalItem", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.NotaFiscal", "NotaFiscal")
                        .WithMany("Itens")
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nota_fiscal_itens_notas_fiscais_nota_fiscal_id");

                    b.Navigation("NotaFiscal");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Orcamento", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .HasConstraintName("fk_orcamentos_clientes_cliente_id");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.OrcamentoItem", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Orcamento", "Orcamento")
                        .WithMany("Itens")
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orcamento_itens_orcamentos_orcamento_id");

                    b.HasOne("GestorAI.API.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .HasConstraintName("fk_orcamento_itens_produtos_produto_id");

                    b.Navigation("Orcamento");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Produto", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_produtos_categorias_categoria_id");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Venda", b =>
                {
                    b.HasOne("GestorAI.API.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Vendas")
                        .HasForeignKey("ClienteId")
                        .HasConstraintName("fk_vendas_clientes_cliente_id");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Contrato", b =>
                {
                    b.Navigation("Cobrancas");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.ContratoTemplate", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.NotaFiscal", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Orcamento", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Produto", b =>
                {
                    b.Navigation("ItensVenda");

                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Profissional", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Disponibilidades");
                });

            modelBuilder.Entity("GestorAI.API.Domain.Entities.Venda", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Lancamento");
                });
#pragma warning restore 612, 618
        }
    }
}
